version: '3'
services:
  node:
    image: riccardobusetti/books-backend:main
    env_file:
      - .env
    ports:
      - 7000:7000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: