name: Publish Docker images

on:
  push:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker meta nginx
        id: docker_meta_nginx
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: riccardobusetti/books-nginx
          tag-sha: true
          tag-edge: false
          tag-latest: true

      - name: Docker meta backend
        id: docker_meta_backend
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: riccardobusetti/books-backend
          tag-sha: true
          tag-edge: false
          tag-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta_nginx.outputs.tags }}
          file: ./nginx/Dockerfile
          context: ./nginx

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta_backend.outputs.tags }}
          file: ./backend/Dockerfile
          context: ./backend

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: books
          environment_name: Books-env
          version_label: "books-deployment-${{ steps.current-time.outputs.time }}"
          region: eu-central-1
          deployment_package: deploy.zip
